### ISSUE TITLE
Can't build on archlinux with 

### ISSUE THREAD

**Issue by bl00dy1837** [kevinboone/uconv#2]
make: Entering directory '/build/uconv-c/src/uconv-0.0.1'
cc -Wall -DVERSION=\"0.0.1\" -DNAME=\"uconv\" -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -o uconv.o -c uconv.c
cc -Wall -DVERSION=\"0.0.1\" -DNAME=\"uconv\" -march=x86-64 -mtune=generic -O2 -pipe -fno-plt -fexceptions         -Wp,-D_FORTIFY_SOURCE=2 -Wformat -Werror=format-security         -fstack-clash-protection -fcf-protection -g -o units.o -c units.c
units.c: In function ‘units_dump’:
units.c:829:5: error: format not a string literal and no format arguments [-Werror=format-security]
  829 |     printf (s);
      |     ^~~~~~
units.c: In function ‘unit_parse_single_unit’:
units.c:579:5: warning: ‘__builtin_strncpy’ specified bound 100 equals destination size [-Wstringop-truncation]
  579 |     strncpy (temp, ss, sizeof (temp));
      |     ^
units.c:606:7: warning: ‘__builtin_strncpy’ specified bound 10 equals destination size [-Wstringop-truncation]
  606 |       strncpy (spower, ss + p, sizeof (spower));
      |       ^
units.c:634:57: warning: ‘%s’ directive output may be truncated writing up to 99 bytes into a region of size 80 [-Wformat-truncation=]
  634 |       snprintf (msg, sizeof (msg), "Unknown unit name: '%s'", sunit);
      |                                                         ^~    ~~~~~
In file included from /usr/include/stdio.h:894,
                 from units.c:8:
In function ‘snprintf’,
    inlined from ‘unit_parse_single_unit’ at units.c:634:7:
/usr/include/bits/stdio2.h:71:10: note: ‘__builtin___snprintf_chk’ output between 22 and 121 bytes into a destination of size 100
   71 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
      |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   72 |                                    __glibc_objsize (__s), __fmt,
      |                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
   73 |                                    __va_arg_pack ());
      |                                    ~~~~~~~~~~~~~~~~~
cc1: some warnings being treated as errors
make: *** [Makefile:20: units.o] Error 1
make: Leaving directory '/build/uconv-c/src/uconv-0.0.1'

**Comment by kevinboone** [comment]
Some of these warnings should already be fixed in the master branch. I have (I hope) fixed the others, and created release version 0.0.3. Please let me know if they are still there.

**Comment by bl00dy1837** [comment]
Thank you! now it works again.
